from __future__ import annotations
import cv2,numpy as np
from . import config
def _components(mask,min_area):
 n,labels,stats,_=cv2.connectedComponentsWithStats(mask,8); out=np.zeros_like(mask); kept=area=0
 for i in range(1,n):
  if stats[i,4]>=min_area: out[labels==i]=255; kept+=1; area+=int(stats[i,4])
 return out,kept,area
def extract_features(image,hsv=None,lab=None,fruit_mask=None):
 hsv=cv2.cvtColor(image,cv2.COLOR_BGR2HSV) if hsv is None else hsv; lab=cv2.cvtColor(image,cv2.COLOR_BGR2LAB) if lab is None else lab
 if fruit_mask is None: raise ValueError("fruit_mask is required")
 inside=fruit_mask>0; total=max(1,int(inside.sum())); h,s,v=cv2.split(hsv); l,a,b=cv2.split(lab)
 green=inside&(h>=config.GREEN_H_MIN)&(h<=config.GREEN_H_MAX)&(s>=config.MIN_COLOR_SATURATION)&(a<=config.GREEN_LAB_A_MAX); yellow=inside&(h>=config.YELLOW_H_MIN)&(h<=config.YELLOW_H_MAX)&(s>=config.MIN_COLOR_SATURATION)&(v>=config.MIN_COLOR_VALUE)&(b>=config.YELLOW_LAB_B_MIN); dark=inside&(v<72)&(s>24); brown=inside&~dark&(h>=config.BROWN_H_MIN)&(h<=config.BROWN_H_MAX)&(s>=35)&(v<205)&(a>=config.BROWN_LAB_A_MIN)&(b>=config.BROWN_LAB_B_MIN); brown&=~green&~yellow
 gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY); local=cv2.GaussianBlur(gray,(0,0),11).astype(np.int16)-gray.astype(np.int16); chroma=np.abs(a.astype(np.int16)-128)+np.abs(b.astype(np.int16)-128); spots=((brown|dark)&(local>=config.LOCAL_SPOT_CONTRAST)&((chroma>24)|brown)).astype(np.uint8)*255; spots=cv2.morphologyEx(spots,cv2.MORPH_OPEN,np.ones((3,3),np.uint8)); spots,count,spot_pixels=_components(spots,max(config.MIN_SPOT_AREA,int(total*config.SPOT_AREA_RATIO)))
 gx=cv2.Sobel(gray,cv2.CV_32F,1,0,ksize=3); gy=cv2.Sobel(gray,cv2.CV_32F,0,1,ksize=3); grad=cv2.magnitude(gx,gy); grad[~inside]=0; values=grad[inside]; texture=float(np.sqrt(np.mean(values**2))/255*10) if values.size else 0; variance=cv2.GaussianBlur(gray.astype(np.float32)**2,(0,0),3)-cv2.GaussianBlur(gray.astype(np.float32),(0,0),3)**2; q=(gray//32).astype(np.int32); valid=inside[:,1:]&inside[:,:-1]; d=np.abs(q[:,1:]-q[:,:-1])[valid]; pct=lambda x:round(float(x.sum())*100/total,1)
 n,labels,stats,_=cv2.connectedComponentsWithStats(spots,8); spot_areas=[int(stats[i,4]) for i in range(1,n) if stats[i,4]>0]; bgr_means=image[inside].mean(axis=0); ys,xs=np.where(inside); aspect=round((xs.max()-xs.min()+1)/max(1,ys.max()-ys.min()+1),3) if xs.size else 0
 cm=np.zeros((*gray.shape,3),np.uint8); cm[inside]=(100,100,100); cm[green]=(70,160,78); cm[yellow]=(35,205,248); cm[brown]=(44,82,132); cm[dark]=(40,40,40)
 return {"green":pct(green),"yellow":pct(yellow),"brown":pct(brown),"dark":pct(dark),"brown_area":pct(brown|dark),"brown_spot_percentage":round(spot_pixels*100/total,1),"spot_count":count,"spot_density":round(count/max(1,total/10000),2),"largest_spot_area":max(spot_areas,default=0),"average_spot_area":round(float(np.mean(spot_areas)),2) if spot_areas else 0,"mean_R":round(float(bgr_means[2]),1),"mean_G":round(float(bgr_means[1]),1),"mean_B":round(float(bgr_means[0]),1),"mean_H":round(float(h[inside].mean()),1),"mean_S":round(float(s[inside].mean()),1),"mean_V":round(float(v[inside].mean()),1),"mean_L":round(float(l[inside].mean()),1),"mean_a":round(float(a[inside].mean()),1),"mean_b":round(float(b[inside].mean()),1),"texture_score":round(texture,2),"gradient_energy":round(float(np.mean(values**2)) if values.size else 0,3),"local_variance":round(float(variance[inside].mean()),2),"glcm_contrast":round(float(np.mean(d.astype(float)**2)) if d.size else 0,3),"glcm_homogeneity":round(float(np.mean(1/(1+d))) if d.size else 0,3),"glcm_energy":round(float(np.mean((1/(1+d))**2)) if d.size else 0,3),"glcm_correlation":round(float(np.corrcoef(q[:,:-1][valid],q[:,1:][valid])[0,1]) if d.size>1 and np.std(q[:,:-1][valid])>0 and np.std(q[:,1:][valid])>0 else 0,3),"fruit_area":total,"fruit_coverage":round(total*100/inside.size,1),"aspect_ratio":aspect,"color_mask":cm,"green_mask":green.astype(np.uint8)*255,"yellow_mask":yellow.astype(np.uint8)*255,"brown_mask":brown.astype(np.uint8)*255,"brown_spot_mask":spots,"gradient":cv2.convertScaleAbs(grad)}
def analyze_colors(hsv,fruit_mask,image=None,lab=None): return extract_features(cv2.cvtColor(hsv,cv2.COLOR_HSV2BGR) if image is None else image,hsv,lab,fruit_mask)
